
# Find pybind11 library (if needed)
if(CHEMICALFUN_BUILD_PYTHON)
	if(${CMAKE_CXX_COMPILER_ID} STREQUAL MSVC)
		find_package(pybind11 2.2.0 REQUIRED PATHS "${CMAKE_CURRENT_SOURCE_DIR}/extern/installed/share/cmake/pybind11")
	else()
		find_package(pybind11 REQUIRED)
	endif()
	if(NOT pybind11_FOUND)
		message(WARNING "Could not find pybind11 - the Python module `chemicalfun` will not be built.")
		set(CHEMICALFUN_BUILD_PYTHON OFF)
	else()
		message(STATUS "Found pybind11 v${pybind11_VERSION}: ${pybind11_INCLUDE_DIRS}")
	endif()
endif()

